### ISSUE TITLE
Twitch Playback Error (Code: -5)

### ISSUE THREAD

**Issue by patrixmith** [Protuhj/myvideobuzz#143]
Are there currently any workarounds to Twitch videos not playing, or any plans to fix the issue?  The error message displayed is: "Video playback failed (Code: -5)".  I have tried playing with video quality settings, but have had no luck.  Roku TV firmware is currently 8.0.0.

**Comment by Protuhj** [comment]
The Roku is displaying the error "no valid bitrates" or something similar when I try to play a Twitch video.  

I'm not sure what the problem is, other than the Roku isn't parsing the HLS manifest correctly, or it thinks it can't decode the video streams in the manifest.  

Twitch will work when I re-do the entire channel (I've tried it) but I'm nowhere near ready to go through with that whole process.

**Comment by Protuhj** [comment]
This should now work again!
